name: Build Pull Request CI

on:
  pull_request:
    branches: ["dev"]

env:
  APPLICATIONPATH: Sumdocs.API

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x
      - name: Build
        run: |
          pushd ${{env.APPLICATIONPATH}}
          dotnet restore
          dotnet build -c Release
          popd
      - name: Test
        run: dotnet test -l "console;verbosity=normal"
